# --- GLOBAL SETTINGS ---
server.port=8084

# Thymeleaf & Messages
spring.thymeleaf.cache=false
spring.messages.cache-duration=0
spring.messages.basename=messages
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.messages.encoding=UTF-8

# Logging
logging.level.com.epam.rd.autocode.spring.project=DEBUG

# JWT Configuration
app.jwt.secret=94a08da45f6e804567e91234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef12345
app.jwt.expiration-ms=86400000

# Active Profile Switch
spring.profiles.active=test