spring.datasource.url=jdbc:postgresql://localhost:5433/bookstore_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

# Explicitly tell Spring to use the PostgreSQL driver
spring.datasource.driver-class-name=org.postgresql.Driver

# Let Spring auto-create and update the tables
# spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=create-drop