CREATE TABLE IF NOT EXISTS EMPLOYEES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    BIRTH_DATE DATE,
    EMAIL VARCHAR(255),
    NAME VARCHAR(255),
    PASSWORD VARCHAR(255),
    PHONE VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS CLIENTS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    BALANCE DECIMAL(10, 2),
    EMAIL VARCHAR(255),
    NAME VARCHAR(255),
    PASSWORD VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS BOOKS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255),
    GENRE VARCHAR(255),
    AGE_GROUP VARCHAR(50),
    PRICE DECIMAL(10, 2),
    PUBLICATION_YEAR DATE,
    AUTHOR VARCHAR(255),
    NUMBER_OF_PAGES INT,
    CHARACTERISTICS VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    LANGUAGE VARCHAR(50)
);