CREATE TABLE IF NOT EXISTS USERS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    DTYPE VARCHAR(31) NOT NULL,
    EMAIL VARCHAR(255),
    NAME VARCHAR(255),
    PASSWORD VARCHAR(255),
    ROLE VARCHAR(50),
    BALANCE DECIMAL(10, 2),
    BIRTH_DATE DATE,
    PHONE VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS BOOKS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255),
    GENRE VARCHAR(255),
    AGE_GROUP VARCHAR(50),
    PRICE DECIMAL(10, 2),
    PUBLICATION_YEAR DATE,
    AUTHOR VARCHAR(255),
    NUMBER_OF_PAGES INT,
    CHARACTERISTICS VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    LANGUAGE VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS ORDERS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID BIGINT,
    SHIPPING_ADDRESS VARCHAR(500),
    CONTACT_PHONE VARCHAR(50),
    RECIPIENT_NAME VARCHAR(255),
    ORDER_DATE TIMESTAMP,
    STATUS VARCHAR(50),
    TOTAL_PRICE DECIMAL(10, 2)
);

CREATE TABLE IF NOT EXISTS ORDER_ITEMS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID BIGINT,
    BOOK_ID BIGINT,
    QUANTITY INT,
    PRICE DECIMAL(10, 2),
    CONSTRAINT FK_ORDER FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ID),
    CONSTRAINT FK_BOOK FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(ID)
);

ALTER TABLE ORDERS ADD CONSTRAINT FK_ORDER_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID);